# Generated by Django 6.0 on 2025-12-29 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место выполнения")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Как часто выполнять (1 - каждый день, т.е. 7 раз в неделю)",
                        verbose_name="Периодичность в днях",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Не должно превышать 120 секунд", verbose_name="Время на выполнение (в секундах)"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Используется только для полезных привычек",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
