# Generated by Django 5.2.9 on 2025-12-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminded",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее напоминание"),
        ),
    ]
